### ISSUE TITLE
List bullets don't appear

### ISSUE THREAD

**Issue by Kenny2github** [smelt-modding/smelt-modding.github.io#16]
#### Expected behavior
The "Known issues" section on [the website](https://smelt-modding.github.io) should show bullet points for lists
#### Actual behavior
The bullet points aren't there
#### Steps to reproduce
Navigate to https://smelt-modding.github.io

**Comment by kerrtravers** [comment]
If the usual ``<ul>`` isn't working, We could try using copy and paste bullet points for now.

**Comment by Kenny2github** [comment]
It's a weird CSS bug, I think. I'm still investigating.

**Comment by kerrtravers** [comment]
@Kenny2github Right 👍

**Comment by bluesbroz** [comment]
It is not a bug, you should use `<li>` instead of `<p>` inside of `<ul>`, and since default value for `list-style-position` is `outside`, list bullets will be outside of the screen ([because all element's padding was reset to 0](https://github.com/smelt-modding/smelt-modding.github.io/blob/master/stylesheet.css#L6) ). You can set `list-style-position: inside` for lists or add `padding-left` for lists or list items.

**Comment by Kenny2github** [comment]
@bluesbroz thank you! I don't know how it became `<p>` instead of `<li>` .-.

**Comment by Kenny2github** [comment]
Nope, that pr didn't fix anything!

**Comment by Kenny2github** [comment]
Yes, that pull worked!
